//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBookDat.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EBookDat.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddBook.
        /// </summary>
        public static string AddBook {
            get {
                return ResourceManager.GetString("AddBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BookDetalis.
        /// </summary>
        public static string BookDetails {
            get {
                return ResourceManager.GetString("BookDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BooksCount.
        /// </summary>
        public static string BooksCount {
            get {
                return ResourceManager.GetString("BooksCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BooksList.
        /// </summary>
        public static string BooksList {
            get {
                return ResourceManager.GetString("BooksList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By.
        /// </summary>
        public static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompaniesCount.
        /// </summary>
        public static string CompaniesCount {
            get {
                return ResourceManager.GetString("CompaniesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComaniesList.
        /// </summary>
        public static string CompaniesList {
            get {
                return ResourceManager.GetString("CompaniesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanyDetails.
        /// </summary>
        public static string CompanyDetails {
            get {
                return ResourceManager.GetString("CompanyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanyManager.
        /// </summary>
        public static string CompanyManager {
            get {
                return ResourceManager.GetString("CompanyManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditBook.
        /// </summary>
        public static string EditBook {
            get {
                return ResourceManager.GetString("EditBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edition.
        /// </summary>
        public static string Edition {
            get {
                return ResourceManager.GetString("Edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditionsDetails.
        /// </summary>
        public static string EditionDetails {
            get {
                return ResourceManager.GetString("EditionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditionManager.
        /// </summary>
        public static string EditionManager {
            get {
                return ResourceManager.GetString("EditionManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditionsCount.
        /// </summary>
        public static string EditionsCount {
            get {
                return ResourceManager.GetString("EditionsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditionsList.
        /// </summary>
        public static string EditionsList {
            get {
                return ResourceManager.GetString("EditionsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExportExcel.
        /// </summary>
        public static string ExportExcel {
            get {
                return ResourceManager.GetString("ExportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string Genre {
            get {
                return ResourceManager.GetString("Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GenreDetails.
        /// </summary>
        public static string GenreDetails {
            get {
                return ResourceManager.GetString("GenreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GenreManager.
        /// </summary>
        public static string GenreManager {
            get {
                return ResourceManager.GetString("GenreManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GenresCount.
        /// </summary>
        public static string GenresCount {
            get {
                return ResourceManager.GetString("GenresCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GenresList.
        /// </summary>
        public static string GenresList {
            get {
                return ResourceManager.GetString("GenresList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImportExcel.
        /// </summary>
        public static string ImportExcel {
            get {
                return ResourceManager.GetString("ImportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN.
        /// </summary>
        public static string ISBN {
            get {
                return ResourceManager.GetString("ISBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        public static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PagesNumber.
        /// </summary>
        public static string PagesNumber {
            get {
                return ResourceManager.GetString("PagesNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        public static string Publisher {
            get {
                return ResourceManager.GetString("Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PublishLocation.
        /// </summary>
        public static string PublishLocation {
            get {
                return ResourceManager.GetString("PublishLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SortBooks.
        /// </summary>
        public static string SortBooks {
            get {
                return ResourceManager.GetString("SortBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SortCompanies.
        /// </summary>
        public static string SortCompanies {
            get {
                return ResourceManager.GetString("SortCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SortEditions.
        /// </summary>
        public static string SortEditions {
            get {
                return ResourceManager.GetString("SortEditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SortGenres.
        /// </summary>
        public static string SortGenres {
            get {
                return ResourceManager.GetString("SortGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting.
        /// </summary>
        public static string Sorting {
            get {
                return ResourceManager.GetString("Sorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified.
        /// </summary>
        public static string Unspecified {
            get {
                return ResourceManager.GetString("Unspecified", resourceCulture);
            }
        }
    }
}
